In [1]:
import pickle
import joblib
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [9]:
df = pd.read_csv('housing1.csv').iloc[:, :-1].dropna()
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0

In [10]:
df.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0
5,-122.25,37.85,52.0,919.0,213.0,413.0,193.0,4.0368,269700.0
6,-122.25,37.84,52.0,2535.0,489.0,1094.0,514.0,3.6591,299200.0
7,-122.25,37.84,52.0,3104.0,687.0,1157.0,647.0,3.1200,241400.0
8,-122.26,37.84,42.0,2555.0,665.0,1206.0,595.0,2.0804,226700.0
9,-122.25,37.84,52.0,3549.0,707.0,1551.0,714.0,3.6912,261100.0

In [12]:
x= df.drop(columns='median_house_value')
y= df.median_house_value.copy()

print(x.shape, y.shape)

(20433, 8) (20433,)

## Train the model

In [13]:
model = LinearRegression()
model.fit(x, y)

LinearRegression()

In [14]:
y_pred = model.predict(x)
y_pred

array([411270.20746022, 415943.95527543, 380534.16332108, ...,
        24989.18869283,  37961.51486097,  55555.76850636], shape=(20433,))

In [15]:
r2_score(y, y_pred)

0.6369116857335635

In [16]:
model

LinearRegression()

# Pickle

In [18]:
with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)

In [19]:
with open('model.pkl', 'rb') as f:
    pickle_model = pickle.load(f)

In [20]:
pickle_model

LinearRegression()

In [21]:
y_pred_pickle = pickle_model.predict(x)
y_pred_pickle

array([411270.20746022, 415943.95527543, 380534.16332108, ...,
        24989.18869283,  37961.51486097,  55555.76850636], shape=(20433,))

In [22]:
r2_score(y, y_pred_pickle)

0.6369116857335635

joblib

In [23]:
joblib.dump(model, 'model.joblib')

['model.joblib']

In [24]:
joblib_model = joblib.load('model.joblib')
joblib_model

LinearRegression()

In [25]:
y_pred_joblib = joblib_model.predict(x)
y_pred_joblib

array([411270.20746022, 415943.95527543, 380534.16332108, ...,
        24989.18869283,  37961.51486097,  55555.76850636], shape=(20433,))

In [26]:
r2_score(y, y_pred_joblib)

0.6369116857335635